### PR TITLE
Shows first semester GPA during second semester

### LINKED ISSUE #70: Show 1st Semester GPA
It would be nice if the 1st semester GPA would be displayed as well during second semester.

### PR DESCRIPTION
**Pull request by insertcustomname**
Closes #70

Uses fetch API to get grade history page and display first semester GPA during second semester.

### CODE REVIEW

**Comment by insertcustomname** [comment]
Can this be merged or do you want me to wait for #112 and use the classes from that instead?

**Comment by gary-kim** [comment]
I've actually just been waiting for a review for that PR. Would you like to try reviewing it?

**Comment by insertcustomname** [comment]
I fixed the race condition, I tried adding the DS_store to the git ignore but not sure if it worked.

**Comment by gary-kim** [comment]
`.DS_Store` should probably be part of your global `.gitignore` but I'd rather have it in the repo `.gitignore` if it means dealing with less Mac users accidentally committing the file.
Also, you need to rebase your branch on top of the current master and remove the commits with dependency bumps. Actually, should I do it for you?

**Comment by insertcustomname** [comment]
Yeah that would be really helpful, thanks!

**Comment by gary-kim** [comment]
@insertcustomname What do you think?

**Comment by insertcustomname** [comment]
Great thanks, can we merge it?

**Pull request merged**
