### PR TITLE
Fixes and cleanups for Course and cumulative GPA

### PR DESCRIPTION
**Pull request by gary-kim**
TODO:
- [ ] Fully fix calculation
    - [x] Fix counting courses without a normal grade
    - Still seems to be a bit off from what it should be. Gonna investigate further.
- [x] Nitpicks
- [x] Migrate to Vue
    - [x] Go to Cialfo for official GPA message

### CODE REVIEW

**Comment by insertcustomname** [comment]
Do you think it would be possible to release the current cumulative-gpa feature with just the fix you made in this PR?

**Comment by gary-kim** [comment]
Whoops, this escaped my mind. Feel free to ping me if it looks like I forgot about something. Let me just get at least the Vue migration done.

**Comment by insertcustomname** [comment]
I checked it out locally but I'm getting this error trying to use webpack:dev:chromum 

ERROR in ./src/js/components/CumulativeGPA.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/js/components/CumulativeGPA.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-loading-template' in '/Users/suhas/Documents/saspes/src/js/components'
 @ ./src/js/components/CumulativeGPA.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/js/components/CumulativeGPA.vue?vue&type=script&lang=js&) 80:0-50 93:16-26
 @ ./src/js/components/CumulativeGPA.vue?vue&type=script&lang=js&
 @ ./src/js/components/CumulativeGPA.vue
 @ ./src/js/saspowerschoolff.js

Not sure what's causing it.

**Comment by insertcustomname** [comment]
Seems to be good, just a question though, does Cialfo include the current semester when calculating? If it doesn't then the extension might be off from Cialfo which might confuse some users.

**Comment by insertcustomname** [comment]
I don't think Cialfo includes semesters in progress GPA but I may be wrong, if it does not it might be good to add something to the disclaimer indicating that Cialfo does not include that whereas the extension does and as such may be different.

**Comment by gary-kim** [comment]
Good point. How about we phrase it like "You can check your official GPA at Cialfo (does not include current semester)"?

**Comment by insertcustomname** [comment]
That sounds good, should be clear enough.

**Pull request merged**
