### PR TITLE
Fix visual bug

### LINKED ISSUE #128: Typing in a percent over 100% in hypothetical assignment causes visual bugs
Hey, just a quick note: I'm @crystalflxme just on another account. Anyways, if you add a hypothetical assignment with a weighting percentage of over 100% it causes the letter grade to not show. Just see for yourself:

image

I know this isn't important at all, but it's just something to polish.

### PR DESCRIPTION
**Pull request by DGET-Program**
Closes #128

Fixing the visual talked about in issue #128

### CODE REVIEW

**Comment by gary-kim** [comment]
Could you add a [DCO](https://github.com/gary-kim/saspes/blob/master/CONTRIBUTING.md#sign-off-your-commit) to your commit? The easiest way would be to add the `-s` flag from the command line. You can run the following command to add a DCO from the head of your commit: `git commit -s --amend` then `git push --force`.
Otherwise, you can also add the following to the bottom of your commit message.
```
Signed-off-by: Random J Developer <random@developer.example.org>
```

In your case, you also have a eslint error so I think it'd be easier to do this:
from the directory of the cloned repo fix the [eslint error](https://travis-ci.com/gary-kim/saspes/jobs/295231183#L287), then run these commands:
```bash
git checkout patch-1
git commit -as --amend --no-edit
git push --force
```
That should change your commit to include the eslint error fix and add your DCO then push it to this branch.

**Comment by gary-kim** [comment]
@DGET-Program It'd be nice to have this as part of the `v0.20.0` release. Any chance you can get that DCO added?

**Comment by DGET-Program** [comment]
I think that I did it correctly, though I'm not sure. It seems that the DCO check passed though I'm not sure what to do about the Travis CI check.

**Comment by gary-kim** [comment]
I can fix that for you. It's just that you're missing a semicolon and eslint is set up to take that as an error.

**Pull request merged**
